[package]
name = "melc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.9.2", features = ["serde"] }
dirs-next = "2.0.0"
